after-login-command = []
after-startup-command = []
start-at-login = true
automatically-unhide-macos-hidden-apps = true

[mode.main.binding]
    alt-s = '''exec-and-forget osascript -e '
tell application "Safari"
    if (count of windows) is 0 then
        make new document at end of documents
    end if
    activate
end tell''''
    alt-enter = 'exec-and-forget open -a Ghostty'

    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-r = 'mode resize'
    alt-space = 'mode service'

[mode.resize.binding]
    j = 'resize smart +50'
    k = 'resize smart -50'
    enter = 'mode main'
    esc = 'mode main'

[mode.service.binding]
    r = ['reload-config', 'mode main']
    f = ['flatten-workspace-tree', 'mode main']
    t = ['layout floating tiling', 'mode main']
    c = ['close-all-windows-but-current', 'mode main']

