set mapleader = ' '
set maplocalleader = ' '
set netrw_banner = false
set errorbells = false
set scrolloff = 10
set mouse = 'nv'
set termguicolors = true
set wrap = false
set number = true
set relativenumber = true
set signcolumn = 'yes'
set expandtab = true
set shiftwidth = 4
set tabstop = 4
set hlsearch = false
set incsearch = true
set ignorecase = true
set completeopt = 'menuone,noselect'
set swapfile = false
