vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.loaded_python3_provider = 0
vim.g.loaded_node_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_ruby_provider = 0
vim.go.errorbells = false
vim.go.incsearch = true
vim.go.scrolloff = 10
vim.go.mouse = 'a'
vim.go.termguicolors = true
vim.wo.wrap = false
vim.wo.number = true
vim.wo.signcolumn = 'yes'
vim.wo.relativenumber = true
vim.bo.expandtab = true
vim.bo.shiftwidth = 4
vim.bo.tabstop = 4
vim.bo.smartindent = true
vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.breakindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.updatetime = 250
vim.o.timeout = true
vim.o.timeoutlen = 300
vim.o.completeopt = 'menuone,noselect'
