vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.netrw_banner = false
vim.go.errorbells = false
vim.go.scrolloff = 10
vim.go.mouse = 'nv'
vim.go.termguicolors = true
vim.wo.wrap = false
vim.wo.number = true
vim.wo.relativenumber = true
vim.wo.signcolumn = 'yes'
vim.bo.expandtab = true
vim.bo.shiftwidth = 4
vim.bo.tabstop = 4
vim.bo.smartindent = true
vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.ignorecase = true
vim.o.completeopt = 'menuone,noselect'
vim.o.swapfile = false
