eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(fzf --zsh)"

PATH="/opt/homebrew/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:$HOME/.local/bin:$PATH"
export PATH

export TERM=tmux-256color
export EDITOR=nvim
export LESSHISTFILE=-
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_STATESEPARATOR=""
export PF_INFO="ascii title os  shell editor memory palette"

