eval "$(/opt/homebrew/bin/brew shellenv)"

PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:$HOME/.local/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:$PATH"
export PATH

export TERM=xterm-256color
export EDITOR=nvim
export LESSHISTFILE=-
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_STATESEPARATOR=""
export PF_INFO="ascii title os  shell editor memory palette"

