PATH="$HOME/.local/bin:$PATH"
export PATH

export TERM="tmux-256color"
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=none
export LESSHISTFILE=-
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_STATESEPARATOR=""
