HISTFILE=~/.zhistory
HISTSIZE=10000
SAVEHIST=10000
setopt nobeep extendedglob nomatch histsavenodups histignorespace
bindkey -v

eval "$(/opt/homebrew/bin/brew shellenv)"
source <(fzf --zsh)

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:${FPATH}
  autoload -Uz compinit; compinit
fi

virtualenv_prompt() {
    [[ "$VIRTUAL_ENV" == "" ]] && return

    local venv_name="${VIRTUAL_ENV##*/}"
    if typeset -f deactivate >/dev/null; then
        echo "%F{8}${venv_name}%f "
    fi
}

source ~/.config/zsh/git-prompt.sh
setopt PROMPT_SUBST
precmd() { __git_ps1 '$(virtualenv_prompt)%B%F{4}%3~%f%b' ' %# ' ' %s'}

alias ls='ls --color=auto'
alias notes='cd ~/Documents/notes'
