HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt extendedglob nomatch notify
bindkey -v

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh-completions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

virtualenv_prompt() {
    [[ "$VIRTUAL_ENV" == "" ]] && return

    local venv_name="${VIRTUAL_ENV##*/}"
    if typeset -f deactivate >/dev/null; then
        echo "%F{8}${venv_name}%f "
    fi
}

# Prompt
source ~/.config/zsh/git-prompt.sh
setopt PROMPT_SUBST
precmd() { __git_ps1 '$(virtualenv_prompt)%B%F{4}%3~%f%b' ' %# ' ' %s'}

# Command Completion and Double-Tab Menu
zstyle :compinstall filename '~/.zshrc'
zstyle ':completion:*' menu select

# Syntax Highlighting and Suggestions
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
alias ls='ls --color=auto'
